version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "127.0.0.1:5433:5432"


        #  rails:
        #    build: .
        #    command: bash -c "rm -f tmp/pids/server.pid && yarn install && rails db:create && rails db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
        #    volumes:
        #      - .:/ArrivalistAudition
        #    ports:
        #      - "3000:3000"
        #    depends_on:
        #      - db
